-- MySQL Script generated by MySQL Workbench
-- Fri Jun 26 16:27:21 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema girls_group
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema girls_group
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `girls_group` DEFAULT CHARACTER SET utf8mb4 ;
USE `girls_group` ;

-- -----------------------------------------------------
-- Table `girls_group`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `girls_group`.`categoria` (
  `id_categoria` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_categoria` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_categoria`),
  UNIQUE INDEX `nome_categoria` (`nome_categoria` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `girls_group`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `girls_group`.`usuario` (
  `id_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_usuario` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `papel` ENUM('Administrador', 'Gerente', 'Tecnico', 'Financeiro', 'Recursos Humanos') NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `girls_group`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `girls_group`.`empresa` (
  `id_empresa` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_empresa` VARCHAR(100) NOT NULL,
  `nome_fantasia` VARCHAR(100) NULL DEFAULT NULL,
  `razao_social` VARCHAR(100) NOT NULL,
  `cnpj` VARCHAR(18) NOT NULL,
  `endereco` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `telefone` VARCHAR(20) NULL DEFAULT NULL,
  `principal_atividade` VARCHAR(255) NULL DEFAULT NULL,
  `historia` TEXT NULL DEFAULT NULL,
  `apresentacao` TEXT NULL DEFAULT NULL,
  `id_usuario` INT(11) NOT NULL,
  PRIMARY KEY (`id_empresa`),
  UNIQUE INDEX `cnpj` (`cnpj` ASC) VISIBLE,
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `empresa_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `girls_group`.`usuario` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `girls_group`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `girls_group`.`produto` (
  `id_produto` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_produto` VARCHAR(100) NOT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `unidade_medida` VARCHAR(50) NULL DEFAULT NULL,
  `id_categoria` INT(11) NOT NULL,
  `id_empresa` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_produto`),
  INDEX `id_empresa` (`id_empresa` ASC) VISIBLE,
  INDEX `id_categoria` (`id_categoria` ASC) VISIBLE,
  CONSTRAINT `produto_ibfk_1`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `girls_group`.`empresa` (`id_empresa`),
  CONSTRAINT `produto_ibfk_2`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `girls_group`.`categoria` (`id_categoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `girls_group`.`foto_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `girls_group`.`foto_produto` (
  `id_foto` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_arquivo` VARCHAR(255) NOT NULL,
  `legenda` VARCHAR(255) NULL DEFAULT NULL,
  `texto_alternativo` VARCHAR(255) NULL DEFAULT NULL,
  `id_produto` INT(11) NOT NULL,
  PRIMARY KEY (`id_foto`),
  INDEX `id_produto` (`id_produto` ASC) VISIBLE,
  CONSTRAINT `foto_produto_ibfk_1`
    FOREIGN KEY (`id_produto`)
    REFERENCES `girls_group`.`produto` (`id_produto`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

ALTER TABLE `usuario` MODIFY COLUMN `papel` ENUM('Admin', 'Colaborador') NOT NULL;
UPDATE `usuario` SET `papel` = 'Admin';
UPDATE `usuario` SET `papel` = 'Admin' WHERE id_usuario > 0;